name: first_try
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_application_1: ^0.0.2
  flutter_bloc: ^9.0.0
  flutter_credit_card: ^4.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: null
  insta_image_viewer: ^1.0.4
  intl: ^0.19.0
  percent_indicator: ^4.2.4
  table_calendar: ^3.1.3
  provider: 
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.2.2
  pull_to_refresh_flutter3: ^2.0.2
  flutter_facebook_auth: ^7.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
          weight: 900


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
  ignore_comments: true
